### PR TITLE
Cleanup the quarkus templates

### PR DESCRIPTION
**Pull request by iocanel**
- Minor changes in the existing templates
- Rename quarkus-wizzard to quarkus-application

### CODE REVIEW

**Comment by cmoulliard** [comment]
I will apply your changes on my project = templates and bring back it under q-shift.
Ok ? @iocanel

**Comment by iocanel** [comment]
@cmoulliard: still we need to merge this one too, so please review/approve.

**Comment by cmoulliard** [comment]
Why do you want to merge this PR AS we don't use this project anymore, that we have now https://github.com/q-shift/qshift-templates ?
What I propose is to move my project https://github.com/ch007m/my-backstage-templates which is working end-to-end top of https://github.com/q-shift/qshift-templates ?

**Comment by iocanel** [comment]
> Why do you want to merge this PR AS we don't use this project anymore, that we have now https://github.com/q-shift/qshift-templates ? What I propose is to move my project https://github.com/ch007m/my-backstage-templates which is working end-to-end top of https://github.com/q-shift/qshift-templates ?

Sooner or later we are going to need direct forks of janus/software-templates to be able to create prs against their repo.

**Comment by iocanel** [comment]
The real question is why we needed a new repo since we already had this one in place :smile:

**Pull request merged**
